### ISSUE TITLE
Doesn't play nice with saved sessions

### ISSUE THREAD

**Issue by sergeypdev** [TheBlob42/drex.nvim#16]
After saving and restoring a session with all buffers, drex buffers get messed up.

![drex drawer after restoring a session](https://user-images.githubusercontent.com/78605863/153937769-5bfb80a5-f604-4826-914c-56c94c471d5b.png)
(icons are ok, it's just how neovim-qt renders them on windows 🤷)

Trying to expand directories doesn't work either. Deleting drex buffers and then restarting neovim helps.

I have an auto-session plugin which automatically creates and restores session, so each time I open vim drex becomes broken.

**Comment by sergeypdev** [comment]
Here's a workaround that seems to work for me when using [auto-session](https://github.com/rmagatti/auto-session)

```viml
function DeleteDrexBuffers()
  let l:buffers = join(map(split(execute('filter /^drex:/ ls!'), "\n"), 'str2nr(v:val)'))

  if !empty(l:buffers)
    echom "Deleting drex buffers " . l:buffers
    execute ':bd! ' . l:buffers
  endif
endfunction


command DeleteDrexBuffers :call DeleteDrexBuffers()

let g:auto_session_pre_save_cmds = ["DeleteDrexBuffers"]

```

**Comment by TheBlob42** [comment]
Nice catch. To be honest I have never saved or restored a session in (Neo)Vim, so I need to have a look into this :thinking:
 
One thing that catches my eye right away is how the file paths look e.g. `C:/lumix_src/src`
As far as I know Windows should use the `\` character to separate file path elements...

Nonetheless something is clearly broken here and I will have a look :detective: 
(good that you have a workaround for now)

**Comment by TheBlob42** [comment]
I have created a branch with a fix that works for me (tested with `auto-session`)

Unfortunately I can not test it properly with a Windows system, so I am not sure that this will solve your problem as well. Could you check out the `fix_session_load` branch and check if this is a solution to your problem?
