### ISSUE TITLE
Support for colored icons

### ISSUE THREAD

**Issue by jasper-schnabel** [TheBlob42/drex.nvim#22]
Hey,

I was wondering if it's possible to add support for colored icons.
`'kyazdani42/nvim-web-devicons'` has an option to get the color of an icon.

Take a look at its README:
![screenshot_2022-04-19_12:15:58](https://user-images.githubusercontent.com/67754783/163982754-22313dd0-ad90-4f03-987a-f58719cd1a1c.png)

It could also be an optional option to set in the config.
If it's against the idea of the plugin feel free to not to include it.

Best regards

**Comment by TheBlob42** [comment]
I do actually like the idea of having colored icons in DREX. I need to check out the documentation about it and how to integrated it within the plugin. As you suggested I would prefer to offer this as a configurable option for those who prefer a more monocromatic look instead.

**Comment by TheBlob42** [comment]
If you update the plugin to the latest version you should now get colored icons by default
If you don't like the colors anymore, you can deactivate it by setting the `colored_icons` option
I think this should cover everything :slightly_smiling_face:

**Comment by jasper-schnabel** [comment]
Thanks a lot, it works perfectly!
