### ISSUE TITLE
When Drex drawer is on the only window it opens files to the left instead of right

### ISSUE THREAD

**Issue by SergeyPoznyakAkvelon** [TheBlob42/drex.nvim#29]
Steps to reproduce:
1. Open any file
2. :DrexDrawerToggle
3. Switch back to file
4. Close window :q
5. Now drex drawer is the only window
6. Open any file from drex
7. Drex drawer ends up on the right

![image](https://user-images.githubusercontent.com/54810387/188635227-5f80c518-b0d0-4d4b-83f0-8be67f1a00ff.png)

**Comment by SergeyPoznyakAkvelon** [comment]
@TheBlob42 nosplitright

**Comment by TheBlob42** [comment]
I have `set splitright` and `set splitbelow` in my vimrc for ages, so I would have never found this "bug" :smile: thanks

**Comment by SergeyPoznyakAkvelon** [comment]
Thank you for such a quick fix!
