### ISSUE TITLE
prevent another buffer hijacking drex drawer window?

### ISSUE THREAD

**Issue by ZenLian** [TheBlob42/drex.nvim#34]
If you open another buffer(e.g. `:edit file`) in drex drawer, the new buffer hijacks drex drawer window.
Is there any way to prevent this happening, like what [neo-tree](https://github.com/nvim-neo-tree/neo-tree.nvim#user-experience-good-slightly_smiling_face-thumbsup) did?

**Comment by TheBlob42** [comment]
I actually hacked together a snippet exactly for this case a few weeks back :slightly_smiling_face: 
You can find it in the wiki [here](https://github.com/TheBlob42/drex.nvim/wiki/Configuration#only-drex-buffers-for-the-drawer). Have a look if this is a sufficient solution for your case or if your missing anything.

I do not know how `neo-tree` actually archives this and I haven't found it after a brief look into their source code. But if somebody has more knowledge about it, I would be interested if their solution does not interfere with the alternate buffer and the jump list :thinking:

**Comment by ZenLian** [comment]
Thanks! And I think you are right, maybe better if it stays in user's configuration.
