### ISSUE TITLE
Can we use floating window for multi_rename action in DrexDrawer buffer?

### ISSUE THREAD

**Issue by ZenLian** [TheBlob42/drex.nvim#35]
`below split` in drex drawer window looks awkward.

![Screenshot_20221213_231441](https://user-images.githubusercontent.com/28292229/207371540-74560db0-e6cc-462d-ae3e-c20f760db141.png)

**Comment by TheBlob42** [comment]
That is a good idea and we can probably already reuse code from the clipboard edit floating window easily. Let me have a look at this

**Comment by TheBlob42** [comment]
I have made this configurable and switched the default to a floating window (as I personally think this makes more sense in general) in 24aca45d2e16715900b6f2d1d09204b835708dae. It is still on the `develop` branch for testing first.

**Comment by ZenLian** [comment]
Thanks! Nice work!
